"""fix tables

Revision ID: 01ab5b43e4bb
Revises: 903349ca6d6c
Create Date: 2021-04-11 18:20:20.710129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01ab5b43e4bb'
down_revision = '903349ca6d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'image')
    op.add_column('test', sa.Column('image', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'image')
    op.add_column('group', sa.Column('image', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
