"""add new tables for easy_spy_system

Revision ID: 0b9dc7a37ac1
Revises: 6e9a9b12c448
Create Date: 2021-06-04 01:05:15.312263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9dc7a37ac1'
down_revision = '6e9a9b12c448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('click_x', sa.Integer(), nullable=True),
    sa.Column('click_y', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('browser_family', sa.String(length=50), nullable=True),
    sa.Column('browser_name', sa.String(length=50), nullable=True),
    sa.Column('browser_version', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_family', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=50), nullable=True),
    sa.Column('device_manufact', sa.String(length=50), nullable=True),
    sa.Column('os_family', sa.String(length=50), nullable=True),
    sa.Column('os_name', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('os_platform', sa.String(length=20), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('screen_depth', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_request_datetime'), 'log_request', ['datetime'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_foreign_key(None, 'user', 'class', ['id_class'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_log_request_datetime'), table_name='log_request')
    op.drop_table('log_request')
    op.drop_table('log_click')
    # ### end Alembic commands ###
