"""add difficult column

Revision ID: 12d358194ad0
Revises: d4b0eb5a4fd6
Create Date: 2021-04-18 15:21:07.615092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d358194ad0'
down_revision = 'd4b0eb5a4fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('difficult', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'difficult')
    # ### end Alembic commands ###
