"""update users table

Revision ID: 5c4e250fc71c
Revises: 3d93e73b4145
Create Date: 2021-06-03 17:13:50.090493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4e250fc71c'
down_revision = '3d93e73b4145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('datetime_last', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('sex', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_user_datetime_last'), 'user', ['datetime_last'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_datetime_last'), table_name='user')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'email')
    op.drop_column('user', 'description')
    op.drop_column('user', 'datetime_last')
    # ### end Alembic commands ###
