"""update users table

Revision ID: 6e9a9b12c448
Revises: 5c4e250fc71c
Create Date: 2021-06-03 18:09:32.854689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e9a9b12c448'
down_revision = '5c4e250fc71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_class', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'class', ['id_class'], ['id'])
    op.drop_column('user', 'id_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_group', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'class', ['id_group'], ['id'])
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'id_class')
    # ### end Alembic commands ###
