"""add groups table

Revision ID: 87ebd2fa3d7d
Revises: 55b76cb82606
Create Date: 2021-04-06 15:00:26.079115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ebd2fa3d7d'
down_revision = '55b76cb82606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('datetime_add', sa.DateTime(), nullable=True),
    sa.Column('datetime_upd', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_datetime_add'), 'group', ['datetime_add'], unique=False)
    op.create_index(op.f('ix_group_title'), 'group', ['title'], unique=True)
    op.create_foreign_key(None, 'test', 'group', ['id_group'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_index(op.f('ix_group_title'), table_name='group')
    op.drop_index(op.f('ix_group_datetime_add'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
