"""create users table

Revision ID: 903349ca6d6c
Revises: 87ebd2fa3d7d
Create Date: 2021-04-09 14:25:15.212973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903349ca6d6c'
down_revision = '87ebd2fa3d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('lastname', sa.String(length=32), nullable=True),
    sa.Column('group', sa.String(length=16), nullable=True),
    sa.Column('pass_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=1), nullable=True),
    sa.Column('datetime_red', sa.DateTime(), nullable=True),
    sa.Column('datetime_upd', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_datetime_red'), 'user', ['datetime_red'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('test', sa.Column('annotation', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'test', 'group', ['id_group'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'annotation')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_datetime_red'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
