"""create tests table

Revision ID: 94efb13fe559
Revises: 
Create Date: 2021-04-05 20:36:42.555968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94efb13fe559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('datetime_add', sa.DateTime(), nullable=True),
    sa.Column('datetime_upd', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_datetime_add'), 'test', ['datetime_add'], unique=False)
    op.create_index(op.f('ix_test_name'), 'test', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_name'), table_name='test')
    op.drop_index(op.f('ix_test_datetime_add'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
