"""fix tables

Revision ID: b52ebdc88f4f
Revises: 39f35c43a242
Create Date: 2021-04-12 18:36:47.257030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b52ebdc88f4f'
down_revision = '39f35c43a242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('datetime_add', sa.DateTime(), nullable=True))
    op.drop_index('ix_result_datetime_red', table_name='result')
    op.create_index(op.f('ix_result_datetime_add'), 'result', ['datetime_add'], unique=False)
    op.drop_column('result', 'datetime_red')
    op.add_column('user', sa.Column('datetime_reg', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_datetime_red', table_name='user')
    op.create_index(op.f('ix_user_datetime_reg'), 'user', ['datetime_reg'], unique=False)
    op.drop_column('user', 'datetime_red')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('datetime_red', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_user_datetime_reg'), table_name='user')
    op.create_index('ix_user_datetime_red', 'user', ['datetime_red'], unique=False)
    op.drop_column('user', 'datetime_reg')
    op.add_column('result', sa.Column('datetime_red', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_result_datetime_add'), table_name='result')
    op.create_index('ix_result_datetime_red', 'result', ['datetime_red'], unique=False)
    op.drop_column('result', 'datetime_add')
    # ### end Alembic commands ###
